### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by AvichalTatu** [rasenior/ThermStats#11]
I have been trying to install thermstats but the dependencies 'rgeos', and 'maptools' are unavailable for the latest version of R.

**Comment by rasenior** [comment]
Oh yes, that is indeed a problem. Thank you for flagging it. I will raise this as an issue, but unfortunately it may take me some time to resolve. You may have to use an older version of R if this is urgent.

**Comment by d0rvm0use** [comment]
Hi, just a question, which version of R did you use? I've tried 3.6.3, 3.6.2 and 3.5.3 and rgeos still can't be installed.
