### ISSUE TITLE
Error / ThermStats installation 

### ISSUE THREAD

**Issue by washfaq** [rasenior/ThermStats#4]
Hello, 
I am facing an error while trying to install "Thermstats". 

devtools::install_github("rasenior/ThermStats")

Downloading GitHub repo rasenior/ThermStats@master
Skipping 1 packages not available: HatchedPolygons
√  checking for file 'C:\Users\washfaq\AppData\Local\Temp\RtmpGCyJqS\remotes3e30177e23b6\rasenior-ThermStats-8ad346e/DESCRIPTION' (748ms)
-  preparing 'ThermStats': (1.1s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (391ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ThermStats_0.9.3.tar.gz' (1.8s)
   
Installing package into ‘C:/Users/washfaq/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency 'HatchedPolygons' is not available for package 'ThermStats'
* removing 'C:/Users/washfaq/Documents/R/win-library/3.6/ThermStats'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/washfaq/AppData/Local/Temp/RtmpGCyJqS/file3e3031b0143c/ThermStats_0.9.3.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

> library(ThermStats)
Error in library(ThermStats) : there is no package called ‘ThermStats’

My session information is as below;
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fields_9.8-3     maps_3.3.0       spam_2.2-2       dotCall64_1.0-0  Thermimage_3.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        rstudioapi_0.10   magrittr_1.5      usethis_1.5.0     devtools_2.0.2   
 [6] pkgload_1.0.2     R6_2.4.0          rlang_0.3.4       tools_3.6.0       pkgbuild_1.0.3   
[11] sessioninfo_1.1.1 png_0.1-7         cli_1.1.0         withr_2.1.2       remotes_2.0.4    
[16] yaml_2.2.0        assertthat_0.2.1  digest_0.6.19     rprojroot_1.3-2   crayon_1.3.4     
[21] processx_3.3.1    callr_3.2.0       fs_1.3.1          ps_1.3.0          curl_3.3         
[26] testthat_2.1.1    glue_1.3.1        memoise_1.1.0     tiff_0.1-5        compiler_3.6.0   
[31] desc_1.2.0        backports_1.1.4   prettyunits_1.0.2

Any idea what might be going wrong? Thanks
Waseem

**Comment by rasenior** [comment]
Ooops, it's because HatchedPolygons is a missing dependency. I'll look into this, but in the meantime if you first run:

`devtools::install_github("statnmap/HatchedPolygons")`

And then try again with:

`devtools::install_github("rasenior/ThermStats")`

It should work. Let me know!

**Comment by washfaq** [comment]
Yes, it is installed and working now. Thank you. 

Another question is can we calculate following through ThermStats;
1. lower and higher temperature of Thermal image (required to measure Plant canopy temperature)?
2. Air temperature (Ta) of Thermal Image 
3. Atmospheric vapour pressure deficit 
If yes, can you please share the script.
Will be much grateful for your help. Thanks

**Comment by washfaq** [comment]
Hello, 
while analyzing plant thermal images, I got below error ;

Getting patches
	...calculating neighbourhood weights
Error in spdep::knearneigh(cbind(df$x, df$y), k = 8) : 
  knearneigh: fewer data points than k 

Any idea to fix this error.

**Comment by rasenior** [comment]
Apologies for the delay. I'll respond below to each issue in turn.

> 1. lower and higher temperature of Thermal image (required to measure Plant canopy temperature)?

Yes - any statistic you like (e.g. min, max) can be passed to `get_stats` or `stats_by_group`

> 2. Air temperature (Ta) of Thermal Image

Air temperature is not measured by thermal cameras. This is a parameter required for accurate conversion of the received infrared radiation to a temperature in &deg;C, but it is something that you either estimate or, ideally, measure yourself using a thermometer, datalogger or weather station. The default setting in thermal cameras is usually 25&deg;C. If you want to retrieve what the default setting on your camera *was*, try:

`Thermimage::flirsettings("path/to/your/image")$Info$AtmosphericTemperature`

But note that you can easily change this within `ThermStats::batch_convert`, via the argument `ATemp`

> 3. Atmospheric vapour pressure deficit
>    If yes, can you please share the script.
>    Will be much grateful for your help. Thanks 

Again, you can't measure atmospheric information with a thermal camera. Vapour Pressure Deficit requires measurements of air temperature and relative humidity, which you could get from a whirling hygrometer, hygrochron datalogger or weather station. Another package of mine called `MoistureCalc` (https://github.com/rasenior/MoistureCalc) can calculate VPD from these two values, via the function `calc_VPD`

> while analyzing plant thermal images, I got below error ;
> 
> Getting patches
> ...calculating neighbourhood weights
> Error in spdep::knearneigh(cbind(df$x, df$y), k = 8) :
> knearneigh: fewer data points than k
> 
> Any idea to fix this error.

I couldn't really tell you without seeing the data, but it seems odd that in a thermal image you should have fewer than 8 data points (which is what the error message is suggesting). Would you be able to share an example image with me? You can email it to rebecca.a.senior@gmail.com and I'll take a look.

**Comment by rasenior** [comment]
By the way, the paper describing the `ThermStats` package was just last week accepted for publication, and I think it will help you a lot as you try it out on your own data. I can let you know when it becomes available to view online? It'll be open access
